sudo: required

language: java

services:
  - docker

before_install:
  - pwd
  - mvn clean install
  - echo "Testing Docker Hub credentials"
  - echo "Docker Hub credentials are working"
  - docker pull python:2.7-slim-jessie

script:
  - docker ps -a
